# Generated by Django 4.2.27 on 2026-01-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('jadarah', 'Jadarah'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
                ('posted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
