# Generated by Django 6.0.1 on 2026-01-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_at', '-id']},
        ),
        migrations.AddField(
            model_name='job',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=320, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('jadarah', 'Jadarah'), ('linkedin', 'LinkedIn')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=800),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source', 'posted_at'], name='jobs_job_source_dbc3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'posted_at'], name='jobs_job_is_acti_2e803c_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='uniq_job_source_external_id'),
        ),
    ]
