# Generated by Django 6.0.1 on 2026-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_fetched_at_job_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('jadarah', 'Jadarah'), ('jobzaty', 'JobZaty'), ('linkedin', 'LinkedIn')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('source', 'url'), name='uniq_job_source_url'),
        ),
    ]
