# Generated by Django 6.0.1 on 2026-01-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_source_job_uniq_job_source_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_source_dbc3d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_is_acti_2e803c_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, default='', max_length=800),
        ),
    ]
