# Generated by Django 6.0.1 on 2026-01-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_jobs_job_source_dbc3d4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='uniq_job_source_external_id',
        ),
        migrations.RemoveConstraint(
            model_name='job',
            name='uniq_job_source_url',
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('jadarah', 'Jadarah'), ('jobzaty', 'JobZaty'), ('ewdifh', 'أي وظيفة'), ('linkedin', 'LinkedIn')], db_index=True, max_length=20),
        ),
    ]
