# Generated by Django 6.0.1 on 2026-01-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_uniq_job_source_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source', 'posted_at'], name='jobs_job_source_dbc3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'posted_at'], name='jobs_job_is_acti_2e803c_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('source', 'url'), name='uniq_job_source_url'),
        ),
    ]
