# Generated by Django 5.2.10 on 2026-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_external_id_job_jobs_job_source_dbc3d4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_skills',
            field=models.JSONField(blank=True, help_text='AI-extracted skills list', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated job summary', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
