# Generated by Django 5.2.10 on 2026-02-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_ai_generated_at_job_ai_skills_job_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Raw text extracted from source article (used for AI processing)', null=True),
        ),
    ]
