# Generated by Django 5.2.11 on 2026-02-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
